# Generated by Django 5.0.6 on 2026-06-16 09:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('min_age', models.PositiveIntegerField(verbose_name='Минимальный возраст')),
                ('max_age', models.PositiveIntegerField(verbose_name='Максимальный возраст')),
            ],
            options={
                'verbose_name': 'Возрастная группа',
                'verbose_name_plural': 'Возрастные группы',
            },
        ),
        migrations.CreateModel(
            name='AgeWeightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('min_birth_year', models.PositiveIntegerField(verbose_name='Минимальный год рождения')),
                ('max_birth_year', models.PositiveIntegerField(verbose_name='Максимальный год рождения')),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Минимальный вес (кг)')),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Максимальный вес (кг)')),
                ('bracket_system', models.CharField(choices=[('single_elimination', 'Олимпийская система'), ('round_robin', 'Круговая система'), ('mixed', 'Смешанная система')], default='single_elimination', max_length=20, verbose_name='Система проведения')),
            ],
            options={
                'verbose_name': 'Возрастно-весовая категория',
                'verbose_name_plural': 'Возрастно-весовые категории',
                'ordering': ['gender', 'min_weight'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название турнира')),
                ('sport_type', models.CharField(default='Боевое самбо', max_length=100, verbose_name='Вид спорта')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('bracket_type', models.CharField(choices=[('single_elimination', 'Олимпийская система'), ('round_robin', 'Круговая система')], default='single_elimination', max_length=20, verbose_name='Тип сетки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Название сетки')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('bracket_type', models.CharField(choices=[('single_elimination', 'Олимпийская система'), ('round_robin', 'Круговая система'), ('mixed', 'Смешанная система')], default='single_elimination', max_length=20, verbose_name='Тип сетки')),
                ('current_round', models.PositiveIntegerField(default=1, verbose_name='Текущий раунд')),
                ('total_rounds', models.PositiveIntegerField(default=0, verbose_name='Всего раундов')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Количество участников')),
                ('status', models.CharField(choices=[('generated', 'Сгенерирована'), ('in_progress', 'В процессе'), ('completed', 'Завершена')], default='generated', max_length=20, verbose_name='Статус')),
                ('is_generated', models.BooleanField(default=False, verbose_name='Сгенерирована')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('age_weight_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tournaments.ageweightcategory', verbose_name='Возрастно-весовая категория')),
            ],
            options={
                'verbose_name': 'Сетка',
                'verbose_name_plural': 'Сетки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('club', models.CharField(max_length=200, verbose_name='Клуб')),
                ('coach', models.CharField(max_length=200, verbose_name='Тренер')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fighters', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fighter', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Боец',
                'verbose_name_plural': 'Бойцы',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='BracketNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Раунд')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция')),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='tournaments.bracket', verbose_name='Сетка')),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tournaments.bracketnode', verbose_name='Родительский узел')),
                ('fighter1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bracket_nodes1', to='tournaments.fighter', verbose_name='Боец 1')),
                ('fighter2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bracket_nodes2', to='tournaments.fighter', verbose_name='Боец 2')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_wins', to='tournaments.fighter', verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Узел сетки',
                'verbose_name_plural': 'Узлы сетки',
                'ordering': ['round_number', 'position'],
            },
        ),
        migrations.AddField(
            model_name='bracket',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_wins', to='tournaments.fighter', verbose_name='Победитель'),
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('category', models.CharField(choices=[('1', 'Первая категория'), ('2', 'Вторая категория'), ('3', 'Третья категория'), ('b', 'Всероссийская категория'), ('i', 'Международная категория')], max_length=2, verbose_name='Категория')),
                ('judge_type', models.CharField(choices=[('referee', 'Рефери'), ('side', 'Боковой судья'), ('head', 'Главный судья')], max_length=10, verbose_name='Тип судьи')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='Номер лицензии')),
                ('experience_years', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Стаж (лет)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Судья',
                'verbose_name_plural': 'Судьи',
                'ordering': ['-is_active', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TimerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_duration', models.PositiveIntegerField(choices=[(120, '2 минуты'), (180, '3 минуты'), (300, '5 минуты')], default=180, verbose_name='Длительность раунда (сек)')),
                ('break_duration', models.PositiveIntegerField(choices=[(30, '30 секунд'), (60, '1 минута'), (90, '1.5 минуты')], default=60, verbose_name='Длительность перерыва (сек)')),
                ('number_of_rounds', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Количество раундов')),
                ('warning_sound', models.BooleanField(default=True, verbose_name='Звуковое предупреждение')),
                ('final_warning', models.PositiveIntegerField(default=10, verbose_name='Финальное предупреждение (сек до конца)')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timer_settings', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Настройки таймера',
                'verbose_name_plural': 'Настройки таймеров',
            },
        ),
        migrations.AddField(
            model_name='bracket',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tournaments.tournament', verbose_name='Турнир'),
        ),
        migrations.AddField(
            model_name='ageweightcategory',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_weight_categories', to='tournaments.tournament', verbose_name='Турнир'),
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_check', models.BooleanField(default=False, verbose_name='Прошёл взвешивание')),
                ('documents_check', models.BooleanField(default=False, verbose_name='Документы проверены')),
                ('payment_check', models.BooleanField(default=False, verbose_name='Взнос оплачен')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Допущен к турниру')),
                ('final_place', models.PositiveIntegerField(blank=True, null=True, verbose_name='Итоговое место')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.agegroup', verbose_name='Возрастная группа')),
                ('age_weight_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='tournaments.ageweightcategory', verbose_name='Возрастно-весовая категория')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.fighter', verbose_name='Боец')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Регистрация на турнир',
                'verbose_name_plural': 'Регистрации на турниры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Номер раунда')),
                ('match_number', models.PositiveIntegerField(verbose_name='Номер матча')),
                ('group_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер группы')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершён')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён в')),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.bracket', verbose_name='Сетка')),
                ('participant1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p1', to='tournaments.tournamentregistration', verbose_name='Участник 1')),
                ('participant2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p2', to='tournaments.tournamentregistration', verbose_name='Участник 2')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.tournamentregistration', verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['bracket', 'round_number', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='WeightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Минимальный вес')),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Максимальный вес')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('both', 'Оба пола')], max_length=10, verbose_name='Пол')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_categories', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Весовая категория',
                'verbose_name_plural': 'Весовые категории',
                'unique_together': {('tournament', 'name', 'gender')},
            },
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='weight_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.weightcategory', verbose_name='Весовая категория'),
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_fighter1', models.IntegerField(default=0, verbose_name='Очки бойца 1')),
                ('score_fighter2', models.IntegerField(default=0, verbose_name='Очки бойца 2')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('win_method', models.CharField(blank=True, choices=[('points', 'По очкам'), ('submission', 'Болевой приём'), ('knockout', 'Нокаут'), ('technical_knockout', 'Технический нокаут'), ('disqualification', 'Дисквалификация'), ('walkover', 'Техническая победа'), ('draw', 'Ничья')], max_length=50, verbose_name='Метод победы')),
                ('win_round', models.IntegerField(blank=True, null=True, verbose_name='Раунд победы')),
                ('is_draw', models.BooleanField(default=False, verbose_name='Ничья')),
                ('judge_notes', models.TextField(blank=True, verbose_name='Заметки судьи')),
                ('round_number', models.IntegerField(default=1, verbose_name='Номер раунда')),
                ('match_number', models.IntegerField(default=1, verbose_name='Номер матча')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный бой')),
                ('current_round', models.PositiveIntegerField(default=1, verbose_name='Текущий раунд')),
                ('round_time_remaining', models.PositiveIntegerField(blank=True, null=True, verbose_name='Осталось времени раунда (сек)')),
                ('break_time_remaining', models.PositiveIntegerField(blank=True, null=True, verbose_name='Осталось времени перерыва (сек)')),
                ('is_round_running', models.BooleanField(default=False, verbose_name='Раунд идёт')),
                ('is_break_running', models.BooleanField(default=False, verbose_name='Перерыв идёт')),
                ('timer_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Таймер запущен')),
                ('last_timer_update', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление таймера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_weight_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fights', to='tournaments.ageweightcategory', verbose_name='Категория')),
                ('bracket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fights', to='tournaments.bracket', verbose_name='Сетка')),
                ('next_fight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_fights', to='tournaments.fight', verbose_name='Следующий бой')),
                ('fighter1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_fighter1', to='tournaments.fighter', verbose_name='Боец 1')),
                ('fighter2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_fighter2', to='tournaments.fighter', verbose_name='Боец 2')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_fights', to='tournaments.fighter', verbose_name='Победитель')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fights', to='tournaments.judge', verbose_name='Судья')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Бой',
                'verbose_name_plural': 'Бои',
                'ordering': ['tournament', 'bracket', 'round_number', 'match_number'],
                'unique_together': {('tournament', 'bracket', 'round_number', 'match_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ageweightcategory',
            unique_together={('tournament', 'name', 'gender')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentregistration',
            unique_together={('tournament', 'fighter')},
        ),
    ]
