# Generated by Django 5.0.6 on 2026-07-23 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='documents_check',
        ),
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='payment_check',
        ),
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='weight_check',
        ),
        migrations.CreateModel(
            name='TournamentCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Например: В, Д, О', max_length=10, verbose_name='Код (1 буква)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Чекпоинт турнира',
                'verbose_name_plural': 'Чекпоинты турнира',
                'ordering': ['order'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RegistrationCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Пройден')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_statuses', to='tournaments.tournamentregistration', verbose_name='Регистрация')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentcheckpoint', verbose_name='Чекпоинт')),
            ],
            options={
                'verbose_name': 'Статус чекпоинта',
                'verbose_name_plural': 'Статусы чекпоинтов',
                'unique_together': {('registration', 'checkpoint')},
            },
        ),
    ]
