# Generated by Django 5.0.6 on 2026-07-27 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_tournamentregistration_documents_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='fighter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_fighter1', to='tournaments.fighter', verbose_name='Боец 1'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bracket_type',
            field=models.CharField(choices=[('single_elimination', 'Олимпийская система'), ('round_robin', 'Круговая система'), ('mixed', 'Смешанная система')], default='single_elimination', max_length=20, verbose_name='Тип сетки'),
        ),
    ]
